#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Plank layer=above manage=on border=off
bspc config focus_follows_pointer true

# change color
. "${HOME}/.cache/wal/colors.sh"


bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

bspc config presel_feedback_color "$color1"

# init programs

picom &
$HOME/.config/polybar/docky/launch.sh
killall plank
plank &
feh --bg-fill ~/Imágenes/Wallpapers/595.jpg
